spring:
  microservice-name: sample-application-property-for-base-msa-framework
  redis:
    port: 6379
    host: 169.56.171.68
    password: OIpjz8SOJS
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30

  cache:
    type: redis
