spring:
    sleuth:
        traceId128: true
    sampler:
        probability: 1.0
    zipkin:
        baseUrl: http://zipkin.zipkin:9411
logging:
    pattern:
        level: "%X{traceId} %X{spanId} %5p"