apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: null
    http:
      paths:
      - backend:
          serviceName: msa-project01-app-ms01
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - null
    secretName: null
